using SharpGraphics.GraphicsViews;
using Silk.NET.SDL;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace SharpGraphics.GraphicsViews.SilkNETSDL
{
    public static class SilkNETSDLUtils
    {

        public static MouseButton ToMouseButton(this byte button)
            => button switch
            {
                Sdl.ButtonLeft => MouseButton.Left,
                Sdl.ButtonMiddle => MouseButton.Middle,
                Sdl.ButtonRight => MouseButton.Right,
                Sdl.ButtonX1 => MouseButton.Extra1,
                Sdl.ButtonX2 => MouseButton.Extra2,
                _ => MouseButton.Unspecified,
            };

        public static KeyboardKey ToKeyboardKey(this in Keysym keysym)
            => (KeyCode)keysym.Sym switch
            {
                KeyCode.KUnknown => KeyboardKey.Unspecified,
                KeyCode.KReturn => KeyboardKey.Enter,
                KeyCode.KEscape => KeyboardKey.Escape,
                KeyCode.KBackspace => KeyboardKey.Backspace,
                KeyCode.KTab => KeyboardKey.Tab,
                KeyCode.KSpace => KeyboardKey.Spacebar,

                //KeyCode.KExclaim => ,
                //KeyCode.KQuotedbl =>,
                //KeyCode.KHash =>,
                //KeyCode.KPercent =>,
                //KeyCode.KDollar =>,
                //KeyCode.KAmpersand =>,
                //KeyCode.KQuote =>,
                //KeyCode.KLeftparen =>,
                //KeyCode.KRightparen =>,
                //KeyCode.KAsterisk =>,
                //KeyCode.KPlus =>,
                //KeyCode.KComma =>,
                //KeyCode.KMinus =>,
                //KeyCode.KPeriod =>,
                //KeyCode.KSlash =>,

                KeyCode.K0 => KeyboardKey.Digit0,
                KeyCode.K1 => KeyboardKey.Digit1,
                KeyCode.K2 => KeyboardKey.Digit2,
                KeyCode.K3 => KeyboardKey.Digit3,
                KeyCode.K4 => KeyboardKey.Digit4,
                KeyCode.K5 => KeyboardKey.Digit5,
                KeyCode.K6 => KeyboardKey.Digit6,
                KeyCode.K7 => KeyboardKey.Digit7,
                KeyCode.K8 => KeyboardKey.Digit8,
                KeyCode.K9 => KeyboardKey.Digit9,

                //KeyCode.KColon =>,
                //KeyCode.KSemicolon =>,
                //KeyCode.KLess =>,
                //KeyCode.KEquals =>,
                //KeyCode.KGreater =>,
                //KeyCode.KQuestion =>,
                //KeyCode.KAT =>,
                //KeyCode.KLeftbracket =>,
                //KeyCode.KBackslash =>,
                //KeyCode.KRightbracket =>,
                //KeyCode.KCaret =>,
                //KeyCode.KUnderscore =>,
                //KeyCode.KBackquote =>,

                KeyCode.KA => KeyboardKey.A,
                KeyCode.KB => KeyboardKey.B,
                KeyCode.KC => KeyboardKey.C,
                KeyCode.KD => KeyboardKey.D,
                KeyCode.KE => KeyboardKey.E,
                KeyCode.KF => KeyboardKey.F,
                KeyCode.KG => KeyboardKey.G,
                KeyCode.KH => KeyboardKey.H,
                KeyCode.KI => KeyboardKey.I,
                KeyCode.KJ => KeyboardKey.J,
                KeyCode.KK => KeyboardKey.K,
                KeyCode.KL => KeyboardKey.L,
                KeyCode.KM => KeyboardKey.M,
                KeyCode.KN => KeyboardKey.N,
                KeyCode.KO => KeyboardKey.O,
                KeyCode.KP => KeyboardKey.P,
                KeyCode.KQ => KeyboardKey.Q,
                KeyCode.KR => KeyboardKey.R,
                KeyCode.KS => KeyboardKey.S,
                KeyCode.KT => KeyboardKey.T,
                KeyCode.KU => KeyboardKey.U,
                KeyCode.KV => KeyboardKey.V,
                KeyCode.KW => KeyboardKey.W,
                KeyCode.KX => KeyboardKey.X,
                KeyCode.KY => KeyboardKey.Y,
                KeyCode.KZ => KeyboardKey.Z,
                
                //KeyCode.KCapslock =>,

                KeyCode.KF1 => KeyboardKey.F1,
                KeyCode.KF2 => KeyboardKey.F2,
                KeyCode.KF3 => KeyboardKey.F3,
                KeyCode.KF4 => KeyboardKey.F4,
                KeyCode.KF5 => KeyboardKey.F5,
                KeyCode.KF6 => KeyboardKey.F6,
                KeyCode.KF7 => KeyboardKey.F7,
                KeyCode.KF8 => KeyboardKey.F8,
                KeyCode.KF9 => KeyboardKey.F9,
                KeyCode.KF10 => KeyboardKey.F10,
                KeyCode.KF11 => KeyboardKey.F11,
                KeyCode.KF12 => KeyboardKey.F12,

                KeyCode.KPrintscreen => KeyboardKey.PrintScreen,
                //KeyCode.KScrolllock => KeyboardKey.,
                KeyCode.KPause => KeyboardKey.Pause,
                KeyCode.KInsert => KeyboardKey.Insert,
                KeyCode.KHome => KeyboardKey.Home,
                KeyCode.KPageup => KeyboardKey.PageUp,
                KeyCode.KDelete => KeyboardKey.Delete,
                KeyCode.KEnd => KeyboardKey.End,
                KeyCode.KPagedown => KeyboardKey.PageDown,

                KeyCode.KRight => KeyboardKey.RightArrow,
                KeyCode.KLeft => KeyboardKey.LeftArrow,
                KeyCode.KDown => KeyboardKey.DownArrow,
                KeyCode.KUp => KeyboardKey.UpArrow,

                //KeyCode.KNumlockclear => KeyboardKey.num,
                KeyCode.KKPDivide => KeyboardKey.Divide,
                KeyCode.KKPMultiply => KeyboardKey.Multiply,
                KeyCode.KKPMinus => KeyboardKey.Subtract,
                KeyCode.KKPPlus => KeyboardKey.Add,
                KeyCode.KKPEnter => KeyboardKey.Enter,

                KeyCode.KKP1 => KeyboardKey.NumPad1,
                KeyCode.KKP2 => KeyboardKey.NumPad2,
                KeyCode.KKP3 => KeyboardKey.NumPad3,
                KeyCode.KKP4 => KeyboardKey.NumPad4,
                KeyCode.KKP5 => KeyboardKey.NumPad5,
                KeyCode.KKP6 => KeyboardKey.NumPad6,
                KeyCode.KKP7 => KeyboardKey.NumPad7,
                KeyCode.KKP8 => KeyboardKey.NumPad8,
                KeyCode.KKP9 => KeyboardKey.NumPad9,
                KeyCode.KKP0 => KeyboardKey.NumPad0,

                //KeyCode.KKPPeriod => KeyboardKey.,
                //KeyCode.KApplication = 1073741925,
                //KeyCode.KPower = 1073741926,
                //KeyCode.KKPEquals = 1073741927,

                KeyCode.KF13 => KeyboardKey.F13,
                KeyCode.KF14 => KeyboardKey.F14,
                KeyCode.KF15 => KeyboardKey.F15,
                KeyCode.KF16 => KeyboardKey.F16,
                KeyCode.KF17 => KeyboardKey.F17,
                KeyCode.KF18 => KeyboardKey.F18,
                KeyCode.KF19 => KeyboardKey.F19,
                KeyCode.KF20 => KeyboardKey.F20,
                KeyCode.KF21 => KeyboardKey.F21,
                KeyCode.KF22 => KeyboardKey.F22,
                KeyCode.KF23 => KeyboardKey.F23,
                KeyCode.KF24 => KeyboardKey.F24,

                //KeyCode.KExecute = 1073741940,
                //KeyCode.KHelp = 1073741941,
                //KeyCode.KMenu = 1073741942,
                //KeyCode.KSelect = 1073741943,
                //KeyCode.KStop = 1073741944,
                //KeyCode.KAgain = 1073741945,
                //KeyCode.KUndo = 1073741946,
                //KeyCode.KCut = 1073741947,
                //KeyCode.KCopy = 1073741948,
                //KeyCode.KPaste = 1073741949,
                //KeyCode.KFind = 1073741950,
                //KeyCode.KMute = 1073741951,
                //KeyCode.KVolumeup = 1073741952,
                //KeyCode.KVolumedown = 1073741953,
                //KeyCode.KKPComma = 1073741957,
                //KeyCode.KKPEqualsas400 = 1073741958,
                //KeyCode.KAlterase = 1073741977,
                //KeyCode.KSysreq = 1073741978,
                //KeyCode.KCancel = 1073741979,
                //KeyCode.KClear = 1073741980,
                //KeyCode.KPrior = 1073741981,
                //KeyCode.KReturn2 = 1073741982,
                //KeyCode.KSeparator = 1073741983,
                //KeyCode.KOut = 1073741984,
                //KeyCode.KOper = 1073741985,
                //KeyCode.KClearagain = 1073741986,
                //KeyCode.KCrsel = 1073741987,
                //KeyCode.KExsel = 1073741988,
                //KeyCode.KKP00 = 1073742000,
                //KeyCode.KKP000 = 1073742001,
                //KeyCode.KThousandsseparator = 1073742002,
                //KeyCode.KDecimalseparator = 1073742003,
                //KeyCode.KCurrencyunit = 1073742004,
                //KeyCode.KCurrencysubunit = 1073742005,
                //KeyCode.KKPLeftparen = 1073742006,
                //KeyCode.KKPRightparen = 1073742007,
                //KeyCode.KKPLeftbrace = 1073742008,
                //KeyCode.KKPRightbrace = 1073742009,
                //KeyCode.KKPTab = 1073742010,
                //KeyCode.KKPBackspace = 1073742011,
                //KeyCode.KKPA = 1073742012,
                //KeyCode.KKPB = 1073742013,
                //KeyCode.KKPC = 1073742014,
                //KeyCode.KKPD = 1073742015,
                //KeyCode.KKPE = 1073742016,
                //KeyCode.KKPF = 1073742017,
                //KeyCode.KKPXor = 1073742018,
                //KeyCode.KKPPower = 1073742019,
                //KeyCode.KKPPercent = 1073742020,
                //KeyCode.KKPLess = 1073742021,
                //KeyCode.KKPGreater = 1073742022,
                //KeyCode.KKPAmpersand = 1073742023,
                //KeyCode.KKPDblampersand = 1073742024,
                //KeyCode.KKPVerticalbar = 1073742025,
                //KeyCode.KKPDblverticalbar = 1073742026,
                //KeyCode.KKPColon = 1073742027,
                //KeyCode.KKPHash = 1073742028,
                //KeyCode.KKPSpace = 1073742029,
                //KeyCode.KKPAT = 1073742030,
                //KeyCode.KKPExclam = 1073742031,
                //KeyCode.KKPMemstore = 1073742032,
                //KeyCode.KKPMemrecall = 1073742033,
                //KeyCode.KKPMemclear = 1073742034,
                //KeyCode.KKPMemadd = 1073742035,
                //KeyCode.KKPMemsubtract = 1073742036,
                //KeyCode.KKPMemmultiply = 1073742037,
                //KeyCode.KKPMemdivide = 1073742038,
                //KeyCode.KKPPlusminus = 1073742039,
                //KeyCode.KKPClear = 1073742040,
                //KeyCode.KKPClearentry = 1073742041,
                //KeyCode.KKPBinary = 1073742042,
                //KeyCode.KKPOctal = 1073742043,
                //KeyCode.KKPDecimal = 1073742044,
                //KeyCode.KKPHexadecimal = 1073742045,

                KeyCode.KLctrl => KeyboardKey.LeftControl,
                KeyCode.KLshift => KeyboardKey.LeftShift,
                KeyCode.KLalt => KeyboardKey.LeftAlt,
                //KeyCode.KLgui = 1073742051,
                KeyCode.KRctrl => KeyboardKey.RightControl,
                KeyCode.KRshift => KeyboardKey.RightShift,
                KeyCode.KRalt => KeyboardKey.RightAlt,
                //KeyCode.KRgui = 1073742055,

                //KeyCode.KMode = 1073742081,
                //KeyCode.KAudionext = 1073742082,
                //KeyCode.KAudioprev = 1073742083,
                //KeyCode.KAudiostop = 1073742084,
                //KeyCode.KAudioplay = 1073742085,
                //KeyCode.KAudiomute = 1073742086,
                //KeyCode.KMediaselect = 1073742087,
                //KeyCode.KWww = 1073742088,
                //KeyCode.KMail = 1073742089,
                //KeyCode.KCalculator = 1073742090,
                //KeyCode.KComputer = 1073742091,
                //KeyCode.KACSearch = 1073742092,
                //KeyCode.KACHome = 1073742093,
                //KeyCode.KACBack = 1073742094,
                //KeyCode.KACForward = 1073742095,
                //KeyCode.KACStop = 1073742096,
                //KeyCode.KACRefresh = 1073742097,
                //KeyCode.KACBookmarks = 1073742098,
                //KeyCode.KBrightnessdown = 1073742099,
                //KeyCode.KBrightnessup = 1073742100,
                //KeyCode.KDisplayswitch = 1073742101,
                //KeyCode.KKbdillumtoggle = 1073742102,
                //KeyCode.KKbdillumdown = 1073742103,
                //KeyCode.KKbdillumup = 1073742104,
                //KeyCode.KEject = 1073742105,
                //KeyCode.KSleep = 1073742106,
                //KeyCode.KApp1 = 1073742107,
                //KeyCode.KApp2 = 1073742108,
                //KeyCode.KAudiorewind = 1073742109,
                //KeyCode.KAudiofastforward = 1073742110,
                //KeyCode.KSoftleft = 1073742111,
                //KeyCode.KSoftright = 1073742112,
                //KeyCode.KCall = 1073742113,
                //KeyCode.KEndcall = 1073742114,

                _ => KeyboardKey.Unspecified,
            };

    }
}
